/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/smart_glasses_with_mi_0716092656_texture.glb --types --transform --meta 
Files: public/smart_glasses_with_mi_0716092656_texture.glb [9.8MB] > D:\uiux\smart_glasses_with_mi_0716092656_texture-transformed.glb [839.46KB] (91%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
  }
  materials: {}
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/smart_glasses_with_mi_0716092656_texture-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={(nodes.mesh_0 as THREE.Mesh).geometry} material={(nodes.mesh_0 as THREE.Mesh).material} />
    </group>
  )
}

useGLTF.preload('/smart_glasses_with_mi_0716092656_texture-transformed.glb')
